### PR TITLE
Added maven support

### PR DESCRIPTION
**Pull request by ArturKeska-Xnet**
- Sources moved to maven specific folder (src/main/java and src/main/test).
- Added very simple test case - just to learn how the library works.
- Removed Idea files (sorry I don’t have InteliJ so I’m not able to check it).
- Added ISessionClosedListener - enabling to monitor if the session was closed.

### CODE REVIEW

**Comment by kashifrazzaqui** [comment]
Thanks for the submission, will get back to you in a day.

**Comment by kashifrazzaqui** [comment]
Thanks for submission and the test :) :+1: 
I have a few suggestions that I have mentioned in other comments. But as these are minor changes, I will go ahead and merge your pull request and make those changes myself to master.

Sorry about the .idea files, I didn't expect anyone to actually use this code :)

**Comment by ArturKeska-Xnet** [comment]
Hi, I'm happy to hear that you merged changes.

I will update the code follow your suggestions. Sure you're right that I forgot to remove the local variable. 
Anyway, I found your library very helpful so I think it's not only good for me at the end of the day :smile:

**Comment by ArturKeska-Xnet** [comment]
What I think is not necessary is the null-check in setCloseListener. So I changed it like this. This way one can pass null - that means remove the listener:

``` java
public void setCloseListener(ISessionClosedListener l) {
      _handshaker.setSessionClosedListener(l);  
  }
```

With this approach we have the same convention as in the setSSLListener method:

``` java
public void setSSLListener(ISSLListener l) {
    _worker.setSSLListener(l);
}
```

**Pull request merged**
